@startuml
'https://plantuml.com/class-diagram

class Subject {
   - Observer : Observer[] observer
   + subscribe(Observer)
   + unsubscribe(Observer)
   + notify()
}

Subject o--> Observer

interface Observer{
   + update()
}

class concreteObserver implements Observer{
   + update()
}
@enduml